In [3]:
#Create a NumPy array with values ranging from 0 to 9.
import numpy as np
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Create a 3x3 matrix with random values between 0 and 1.
arr=np.random.randint(0,2,size=(3,3))
arr

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 1]])

In [41]:
#Reshape a 1D array into a 2D array with dimensions 2x4.
a=np.arange(0,8)
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [2]:
#Extract all the even elements from an array.
l =[0,1,2,3,4,5,6]
l[::2]

[0, 2, 4, 6]

In [24]:
#2.Array Indexing and Slicing
#Retrieve the first row of a 2D array.
import numpy as np
a1 = np.array([[1, 2], [3, 4]])
a1[1]

array([3, 4])

In [15]:
#Get the last column of a 2D array.
a1[:,1:]

array([[2],
       [4]])

In [33]:
#Slice a 1D array to get elements from index 2 to 5.
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[2:6]

array([3, 4, 5, 6])

In [37]:
#Extract a sub-matrix from a 2D array by specifying row and column indices.
arr=np.random.randint(1,10,size=(5,5))
arr[1:4,1:4]

array([[8, 3, 2],
       [1, 4, 8],
       [3, 6, 4]])

In [43]:
#Array Operations:
#Perform element-wise addition and subtraction between two arrays.
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
a+b

array([[ 4,  6],
       [ 8, 10]])

In [42]:
a-b

array([[-4, -4],
       [-4, -4]])

In [45]:
#Multiply a scalar value with a NumPy array.
import numpy as np
a1=np.array([1,2,3,4,5])
n=5
a1*n

array([ 5, 10, 15, 20, 25])

In [48]:
#Calculate the dot product of two matrices.
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
a.dot(b)

array([[ 6,  7],
       [26, 31]])

In [49]:
#Find the mean, median, and standard deviation of an array.
import numpy as np
array = np.arange(10)
print(array)
r1 = np.mean(array)
print("\nMean: ", r1)
r2 = np.std(array)
print("\nstd: ", r2)



[0 1 2 3 4 5 6 7 8 9]

Mean:  4.5

std:  2.8722813232690143


In [50]:
#Array Filtering and Boolean Indexing:
#Create a Boolean mask to extract all values greater than a certain threshold in an array.
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Create a Boolean mask
mask = arr > 3

# Apply the mask to the original array
result = arr[mask]

print(result)

[4 5]


In [57]:
#Count the number of True values in a Boolean array.
import numpy as np
boolarr = np.array([[True,False,True], [False,False,True], [True, False,False]])
boolarr.sum()

4

In [63]:
#Use Boolean indexing to replace all negative values in an array with 0.
import numpy as np
arr = np.array([[-1, 2, -3], [4, -5, 6], [-7, 8, -9]])
# set negative values to zero
arr[arr < 0] = 0
# display the array
print(arr)


[[0 2 0]
 [4 0 6]
 [0 8 0]]


In [ ]:
#Array Aggregation and Statistics:
#Find the maximum and minimum values in an array.
