In [3]:
#1.Array Creation and Manipulation:

#Create a NumPy array with values ranging from 0 to 9.
import numpy as np
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Create a 3x3 matrix with random values between 0 and 1.
arr=np.random.randint(0,2,size=(3,3))
arr

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 1]])

In [41]:
#Reshape a 1D array into a 2D array with dimensions 2x4.
a=np.arange(0,8)
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [2]:
#Extract all the even elements from an array.
l =[0,1,2,3,4,5,6]
l[::2]

[0, 2, 4, 6]

In [24]:
#2.Array Indexing and Slicing:

#Retrieve the first row of a 2D array.
import numpy as np
a1 = np.array([[1, 2], [3, 4]])
a1[1]

array([3, 4])

In [15]:
#Get the last column of a 2D array.
a1[:,1:]

array([[2],
       [4]])

In [33]:
#Slice a 1D array to get elements from index 2 to 5.
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[2:6]

array([3, 4, 5, 6])

In [37]:
#Extract a sub-matrix from a 2D array by specifying row and column indices.
arr=np.random.randint(1,10,size=(5,5))
arr[1:4,1:4]

array([[8, 3, 2],
       [1, 4, 8],
       [3, 6, 4]])

In [43]:
#3.Array Operations:

#Perform element-wise addition and subtraction between two arrays.
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
a+b

array([[ 4,  6],
       [ 8, 10]])

In [42]:
a-b

array([[-4, -4],
       [-4, -4]])

In [45]:
#Multiply a scalar value with a NumPy array.
import numpy as np
a1=np.array([1,2,3,4,5])
n=5
a1*n

array([ 5, 10, 15, 20, 25])

In [48]:
#Calculate the dot product of two matrices.
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
a.dot(b)

array([[ 6,  7],
       [26, 31]])

In [49]:
#Find the mean, median, and standard deviation of an array.
import numpy as np
array = np.arange(10)
print(array)
r1 = np.mean(array)
print("\nMean: ", r1)
r2 = np.std(array)
print("\nstd: ", r2)



[0 1 2 3 4 5 6 7 8 9]

Mean:  4.5

std:  2.8722813232690143


In [50]:
#4.Array Filtering and Boolean Indexing:

#Create a Boolean mask to extract all values greater than a certain threshold in an array.
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Create a Boolean mask
mask = arr > 3

# Apply the mask to the original array
result = arr[mask]

print(result)

[4 5]


In [57]:
#Count the number of True values in a Boolean array.
import numpy as np
boolarr = np.array([[True,False,True], [False,False,True], [True, False,False]])
boolarr.sum()

4

In [63]:
#Use Boolean indexing to replace all negative values in an array with 0.
import numpy as np
arr = np.array([[-1, 2, -3], [4, -5, 6], [-7, 8, -9]])
# set negative values to zero
arr[arr < 0] = 0
# display the array
print(arr)


[[0 2 0]
 [4 0 6]
 [0 8 0]]


In [1]:
#5.Array Aggregation and Statistics:

#Find the maximum and minimum values in an array.
arr = [1, 2, 3, 4, 5]
minimum = min(arr)
maximum = max(arr)
print(f"Minimum value: {minimum}")
print(f"Maximum value: {maximum}")

Minimum value: 1
Maximum value: 5


In [2]:
#Calculate the sum and product of all elements in a 2D array.
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
sum_of_elements = np.sum(arr)
product_of_elements = np.prod(arr)

print(f"The sum of all elements in the array is {sum_of_elements}.")
print(f"The product of all elements in the array is {product_of_elements}.")


The sum of all elements in the array is 21.
The product of all elements in the array is 720.


In [3]:
#Compute the cumulative sum along a specific axis of a 2D array.
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

cumulative_sum_axis0 = np.cumsum(arr, axis=0)

cumulative_sum_axis1 = np.cumsum(arr, axis=1)

print("Cumulative Sum along Axis 0 (columns):")
print(cumulative_sum_axis0)

print("\nCumulative Sum along Axis 1 (rows):")
print(cumulative_sum_axis1)


Cumulative Sum along Axis 0 (columns):
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]

Cumulative Sum along Axis 1 (rows):
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [4]:
#Calculate the correlation coefficient between two arrays.
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)


Correlation Coefficient: -0.9999999999999999


In [5]:
#6.Array Sorting and Searching:

#Sort a 1D array in ascending and descending order.
import numpy as np

# Create a sample 1D array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# Sort the array in ascending order
sorted_arr_ascending = np.sort(arr)

# Sort the array in descending order
sorted_arr_descending = np.sort(arr)[::-1]

print("Original Array:", arr)
print("Ascending Order:", sorted_arr_ascending)
print("Descending Order:", sorted_arr_descending)


Original Array: [3 1 4 1 5 9 2 6 5 3 5]
Ascending Order: [1 1 2 3 3 4 5 5 5 6 9]
Descending Order: [9 6 5 5 5 4 3 3 2 1 1]


In [6]:
#Find the indices that would sort an array.
import numpy as np

# Create a sample 1D array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# Find the indices that would sort the array
sorted_indices = np.argsort(arr)

print("Original Array:", arr)
print("Indices that would sort the array:", sorted_indices)


Original Array: [3 1 4 1 5 9 2 6 5 3 5]
Indices that would sort the array: [ 1  3  6  0  9  2  4  8 10  7  5]


In [7]:
#Search for the index of a specific element in an array.
import numpy as np

# Create a sample numpy array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# Find the index of a specific element (e.g., value 4)
element_to_find = 4
index = np.where(arr == element_to_find)[0]

if index.size > 0:
    print(f"Element {element_to_find} found at index {index[0]}.")
else:
    print(f"Element {element_to_find} not found in the array.")


Element 4 found at index 2.


In [8]:
#Check if all elements in an array satisfy a certain condition.
import numpy as np

# Create a sample numpy array
arr = np.array([3, 5, 7, 9, 11, 13])

# Check if all elements are greater than 2
condition = np.all(arr > 2)

if condition:
    print("All elements in the array are greater than 2.")
else:
    print("Not all elements in the array are greater than 2.")


All elements in the array are greater than 2.


In [13]:
#7.Array Broadcasting:

#Explain the concept of broadcasting in NumPy and provide an example.
'''Broadcasting is a powerful concept in NumPy that allows you to perform element-wise operations on arrays of different shapes, even if they do not have the same shape or dimensions.
Broadcasting essentially extends smaller arrays to match the shape of larger arrays so that element-wise operations can be performed without explicitly creating copies of the smaller array.

The key idea behind broadcasting is that NumPy automatically aligns dimensions of arrays when performing operations, provided certain rules are met
'''

import numpy as np

# Create a 2D array
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 1D array
B = np.array([10, 20, 30])

# Add the 1D array to the 2D array
result = A + B

print(result)


[[11 22 33]
 [14 25 36]]


In [16]:
#Perform operations involving arrays with different shapes using broadcasting.
import numpy as np

# Create a 2D array
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 1D array
B = np.array([10, 20, 30])

# Addition
addition_result = A + B

# Subtraction
subtraction_result = A - B

# Multiplication
C = np.array([[2],
              [4]])
multiplication_result = A * C

# Division
D = np.array([[2, 5, 10]])
division_result = A / D

print("Original Array A:")
print(A)

print("\n1D Array B:")
print(B)

print("\nAddition Result (A + B):")
print(addition_result)

print("\nSubtraction Result (A - B):")
print(subtraction_result)

print("\nMultiplication Result (A * C):")
print(multiplication_result)

print("\nDivision Result (A / D):")
print(division_result)

Original Array A:
[[1 2 3]
 [4 5 6]]

1D Array B:
[10 20 30]

Addition Result (A + B):
[[11 22 33]
 [14 25 36]]

Subtraction Result (A - B):
[[ -9 -18 -27]
 [ -6 -15 -24]]

Multiplication Result (A * C):
[[ 2  4  6]
 [16 20 24]]

Division Result (A / D):
[[0.5 0.4 0.3]
 [2.  1.  0.6]]


In [18]:
#8.Array Concatenation and Splitting:

#Concatenate two arrays vertically and horizontally.
import numpy as np

# Create two sample arrays
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Vertical concatenation
vertical_concatenation = np.vstack((array1, array2))

print("Vertical Concatenation:")
print(vertical_concatenation)

# Horizontal concatenation
horizontal_concatenation = np.hstack((array1, array2))

print("Horizontal Concatenation:")
print(horizontal_concatenation)


Vertical Concatenation:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Concatenation:
[[1 2 5 6]
 [3 4 7 8]]


In [19]:
#Split an array into multiple sub-arrays along a specified axis.
import numpy as np

# Create a sample array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split the array into 5 equally sized sub-arrays along the specified axis (axis=0)
subarrays = np.split(arr, 5)

# Print the sub-arrays
for i, subarray in enumerate(subarrays):
    print(f"Subarray {i + 1}:", subarray)


Subarray 1: [1 2]
Subarray 2: [3 4]
Subarray 3: [5 6]
Subarray 4: [7 8]
Subarray 5: [ 9 10]


In [20]:
#9.Random Number Generation:

#Generate an array of random integers within a specific range.
import numpy as np

# Define the range and size of the random integer array
low_limit = 1  # Minimum value (inclusive)
high_limit = 100  # Maximum value (exclusive)
array_size = 10  # Number of random integers

# Generate the random integer array
random_integers = np.random.randint(low_limit, high_limit, size=array_size)

# Print the generated array
print("Random Integers:", random_integers)


Random Integers: [13 57 55 92  7 15 48 56 63 75]


In [21]:
#Create a random 2D array with a normal distribution.
import numpy as np

# Define the parameters for the normal distribution
mean = 0  # Mean of the distribution
std_dev = 1  # Standard deviation of the distribution
shape = (3, 4)  # Shape of the 2D array (3 rows, 4 columns)

# Create a random 2D array with a normal distribution
random_2d_array = np.random.normal(mean, std_dev, size=shape)

# Print the generated 2D array
print("Random 2D Array with Normal Distribution:")
print(random_2d_array)


Random 2D Array with Normal Distribution:
[[-0.17494876 -0.764322   -0.5101228  -0.61645806]
 [-1.09758856 -2.77069659  1.00797011 -0.28698036]
 [ 0.06550299 -0.22036571  0.57574865  0.12909346]]
