In [2]:
n=int(input("Enter a Number:"))
if n>1:
    for i in range(2,n):
        if n%2==0:
            print(n,"is not prime")
            break
    else:
        print(n, "is prime")
        

Enter a Number:2
2 is prime


In [15]:
num = int(input("Enter a number: "))
sum = 0
ln=len(str(num))
temp = num
while temp > 0:
   digit = temp % 10
   sum += (digit)**ln
   temp //= 10

# display the result
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

Enter a number: 5
5 is an Armstrong number


In [13]:
year=int(input("Enter year to be checked:"))
if(year%4==0 and year%100!=0 or year%400==0):
    print("The year is a leap year!")
else:
    print("The year isn't a leap year!")

Enter year to be checked:2004
The year is a leap year!


In [1]:
import numpy as np

X = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

Y = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

result = np.array(X) + np.array(Y)

print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [9]:
from sympy import Matrix

X = [[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]]

Y = [[9, 8, 7],
	[6, 5, 4],
	[3, 2, 1]]

matrix_x = Matrix(X)
matrix_y = Matrix(Y)

result = matrix_x + matrix_y
print(result)


Matrix([[10, 10, 10], [10, 10, 10], [10, 10, 10]])


In [4]:
X = [[1,2,3],
	[4 ,5,6],
	[7 ,8,9]]

Y = [[4,8,3],
	[1,2,4],
	[7,1,5]]


result= [[0,0,0],
		[0,0,0],
		[0,0,0]]

for i in range(len(X)):

	for j in range(len(X[0])):
		result[i][j] = X[i][j] + Y[i][j]

for r in result:
	print(r)


[5, 10, 6]
[5, 7, 10]
[14, 9, 14]


In [7]:
a=[[5,7],
    [0,1]]
b=[[1,2],
    [4,3]]
temp=[[0,0],
       [0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        temp[i][j]=a[i][j]+b[i][j]
for r in temp:
    print(r)

[6, 9]
[4, 4]
