In [4]:
import numpy as np

In [5]:
# array
a=[[1,2,3],
   [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [6]:
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.shape

(2, 3)

In [8]:
arr.size

6

In [9]:
arr.ndim

2

In [11]:
#arange
arr=np.arange(10,20,.3)
arr

array([10. , 10.3, 10.6, 10.9, 11.2, 11.5, 11.8, 12.1, 12.4, 12.7, 13. ,
       13.3, 13.6, 13.9, 14.2, 14.5, 14.8, 15.1, 15.4, 15.7, 16. , 16.3,
       16.6, 16.9, 17.2, 17.5, 17.8, 18.1, 18.4, 18.7, 19. , 19.3, 19.6,
       19.9])

In [12]:
#linspace
a=np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [13]:
#10->5,2->2,5->10,1->1,10
a.reshape(5,4)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [14]:
a.reshape(10,2)

array([[ 1.        ,  1.47368421],
       [ 1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105],
       [ 3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474],
       [ 7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158],
       [ 9.52631579, 10.        ]])

In [16]:
a=np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [17]:
a.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
a,b

(array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]))

In [19]:
a*b

array([[ 0,  5],
       [12, 21]])

In [20]:
a.dot(b)

array([[ 6,  7],
       [26, 31]])