In [48]:
a.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a.ndim

1

In [55]:
a=np.linspace(1,27,20)
a

array([ 1.        ,  2.36842105,  3.73684211,  5.10526316,  6.47368421,
        7.84210526,  9.21052632, 10.57894737, 11.94736842, 13.31578947,
       14.68421053, 16.05263158, 17.42105263, 18.78947368, 20.15789474,
       21.52631579, 22.89473684, 24.26315789, 25.63157895, 27.        ])

In [58]:
a.ndim

1

In [1]:
import numpy as np

In [11]:
arr=np.random.randint(1,10,size=(5,5))
arr

array([[1, 5, 4, 4, 7],
       [1, 5, 3, 3, 8],
       [8, 6, 1, 2, 8],
       [8, 1, 1, 8, 3],
       [1, 5, 6, 7, 3]])

In [12]:
arr[1]

array([1, 5, 3, 3, 8])

In [13]:
arr[1,1]

5

In [14]:
arr[1:4,1]

array([5, 6, 1])

In [15]:
arr[1:4,1:3]

array([[5, 3],
       [6, 1],
       [1, 1]])

In [17]:
arr[2:,3:]

array([[2, 8],
       [8, 3],
       [7, 3]])

In [18]:
arr[:,::4]

array([[1, 7],
       [1, 8],
       [8, 8],
       [8, 3],
       [1, 3]])

In [21]:
arr

array([[1, 5, 4, 4, 7],
       [1, 5, 3, 3, 8],
       [8, 6, 1, 2, 8],
       [8, 1, 1, 8, 3],
       [1, 5, 6, 7, 3]])

In [28]:
arr[::4,::4]

array([[1, 7],
       [1, 3]])