In [3]:
#Array Manipulation: Implement a function that takes a 2D numpy array as input and rotates it 90 degrees clockwise without using any numpy functions for rotation.

import numpy as np

def rotate_90_degrees_clockwise(arr):
    if len(arr) == 0:
        return arr

    # Get the dimensions of the input array
    rows, cols = len(arr), len(arr[0])

    # Create a new array with swapped dimensions
    rotated_arr = np.empty((cols, rows), dtype=arr.dtype)

    # Fill in the values of the rotated array
    for i in range(rows):
        for j in range(cols):
            rotated_arr[j][rows - 1 - i] = arr[i][j]

    return rotated_arr

# Example usage:
input_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = rotate_90_degrees_clockwise(input_array)
print(result)


[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [4]:
#Advanced Array Indexing: Given a numpy array, create a new array that contains the elements from the original array where the corresponding elements meet specific conditions (e.g., greater than 10 and less than 50).

import numpy as np

# Create a sample numpy array
original_array = np.array([1, 20, 30, 5, 15, 40, 60])

# Define the conditions
condition = (original_array > 10) & (original_array < 50)

# Create a new array containing elements that meet the conditions
new_array = original_array[condition]

# Print the new array
print(new_array)


[20 30 15 40]


In [5]:
Multidimensional Array Operations: Create a numpy array with shape (n, n) where n is an odd number. Fill it with zeros except for the center element, which should be 1. Implement a function to perform a 2D convolution operation on this array using a predefined kernel.

import numpy as np
from scipy.signal import convolve2d

def create_odd_centered_array(n):
    if n % 2 == 0:
        raise ValueError("n must be an odd number.")
    
    center = (n - 1) // 2  # Calculate the center index
    array = np.zeros((n, n), dtype=int)
    array[center, center] = 1
    return array

def perform_2d_convolution(input_array, kernel):
    result = convolve2d(input_array, kernel, mode='same', boundary='wrap')
    return result

# Create a 5x5 array with a center element of 1
n = 5
input_array = create_odd_centered_array(n)

# Define a kernel for convolution (example kernel)
kernel = np.array([[1, 1, 1],
                   [1, 0, 1],
                   [1, 1, 1]])

# Perform the 2D convolution
convolved_array = perform_2d_convolution(input_array, kernel)

# Print the original array and the result of convolution
print("Original Array:")
print(input_array)
print("\nResult of Convolution:")
print(convolved_array)


Original Array:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Result of Convolution:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [8]:
#Efficient Sorting:Create a custom sorting algorithm that sorts a numpy array of integers in ascending order. Compare its performance with numpy's built-in sorting functions for large arrays.

import numpy as np
import time

def custom_bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        swapped = False
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True
        if not swapped:
            break

# Generate a large random NumPy array of integers
np.random.seed(0)
large_array = np.random.randint(0, 1000, size=10000)

# Copy the array for custom sorting (to keep the original unsorted)
custom_sorted_array = large_array.copy()

# Measure time for custom sorting
start_time = time.time()
custom_bubble_sort(custom_sorted_array)
custom_sort_time = time.time() - start_time

# Copy the array again for NumPy sorting
numpy_sorted_array = large_array.copy()

# Measure time for NumPy sorting
start_time = time.time()
numpy_sorted_array.sort()
numpy_sort_time = time.time() - start_time

# Verify that both sorting methods produce the same result
assert np.array_equal(custom_sorted_array, numpy_sorted_array)

print(f"Custom Sorting Time: {custom_sort_time:.6f} seconds")
print(f"NumPy Sorting Time: {numpy_sort_time:.6f} seconds")


Custom Sorting Time: 43.128390 seconds
NumPy Sorting Time: 0.001027 seconds


In [18]:
#Array Serialization:Develop a mechanism to efficiently serialize and deserialize numpy arrays to/from disk in a custom binary format. Include error-checking and compatibility features.
import numpy as np
import struct

def serialize_numpy_array(array, filename):
    header = struct.pack('Q', array.size)  # Store the number of elements as an unsigned long long
    header += struct.pack('B', array.dtype.itemsize)  # Store the data type size as a byte
    header += struct.pack('B', array.ndim)  # Store the number of dimensions as a byte
    header += struct.pack(f'{array.ndim}I', *array.shape)  # Store the shape as a sequence of unsigned integers

    with open(filename, 'wb') as file:
        file.write(header)
        file.write(array.tobytes())

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
serialize_numpy_array(arr, 'serialized_array.bin')

def deserialize_numpy_array(filename):
    with open(filename, 'rb') as file:
        num_elements = struct.unpack('Q', file.read(8))[0]
        dtype_size = struct.unpack('B', file.read(1))[0]
        num_dims = struct.unpack('B', file.read(1))[0]
        shape = struct.unpack(f'{num_dims}I', file.read(num_dims * 4))
        
        # Calculate the shape and dtype
        shape = tuple(shape)
        dtype = f'int{dtype_size * 8}'
        
        # Create an empty array
        array = np.empty(shape, dtype=dtype)
        
        # Read the binary data and populate the array
        file.readinto(array)
        
        return array

# Example usage:
loaded_array = deserialize_numpy_array('serialized_array.bin')
print(loaded_array)



[[1 2 3]
 [4 5 6]]


In [14]:
#Array Customization:Extend numpy by implementing a custom numpy-like data structure with unique mathematical operations or array manipulation techniques tailored to a specific domain or problem. 

class SparseMatrix:
    def __init__(self, data, row_indices, col_indices, shape):
        self.data = data  # List of non-zero values
        self.row_indices = row_indices  # List of row indices corresponding to data
        self.col_indices = col_indices  # List of column indices corresponding to data
        self.shape = shape  # Shape of the matrix (rows, columns)

    def to_dense(self):
        dense_matrix = np.zeros(self.shape, dtype=float)
        for i in range(len(self.data)):
            dense_matrix[self.row_indices[i], self.col_indices[i]] = self.data[i]
        return dense_matrix

    def transpose(self):
        # Transpose the matrix by swapping row and column indices
        return SparseMatrix(self.data, self.col_indices, self.row_indices, self.shape[::-1])

    def dot(self, other_matrix):
        # Perform a dot product between two sparse matrices
        if self.shape[1] != other_matrix.shape[0]:
            raise ValueError("Matrix dimensions are not compatible for dot product.")
        
        # Perform the dot product efficiently
        result_data = []
        result_row_indices = []
        result_col_indices = []
        
        # Perform dot product calculations here...
        
        return SparseMatrix(result_data, result_row_indices, result_col_indices, (self.shape[0], other_matrix.shape[1]))

    def __str__(self):
        return f"SparseMatrix(shape={self.shape}, nnz={len(self.data)})"

# Example usage:
data = [1.0, 2.0, 3.0]
row_indices = [0, 1, 2]
col_indices = [0, 1, 2]
shape = (3, 3)

sparse_matrix = SparseMatrix(data, row_indices, col_indices, shape)
dense_matrix = sparse_matrix.to_dense()
print(sparse_matrix)
print(dense_matrix)


SparseMatrix(shape=(3, 3), nnz=3)
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
